# Generated by Django 4.0.6 on 2022-07-07 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monarp_places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='name')),
                ('icon', models.ImageField(upload_to='places/services/img', verbose_name='icon')),
            ],
        ),
        migrations.RenameField(
            model_name='place',
            old_name='notes',
            new_name='description',
        ),
        migrations.AddField(
            model_name='place',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='place',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_places', to=settings.AUTH_USER_MODEL, verbose_name='reported by'),
        ),
        migrations.AlterField(
            model_name='place',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_places', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='place',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.CreateModel(
            name='PlaceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_from', models.TimeField(default='0:00', verbose_name='open from')),
                ('open_until', models.TimeField(default='0:00', verbose_name='open until')),
                ('price', models.DecimalField(decimal_places=2, help_text="in local currency only, set zero for free, don't enter if unknown", max_digits=12, verbose_name='price')),
                ('price_range', models.PositiveSmallIntegerField(choices=[(0, 'free'), (1, 'dirty cheap'), (2, 'cheap'), (3, 'affordable'), (4, 'expensive'), (5, 'sky high')], default=0, verbose_name='price range')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='monarp_places.place', verbose_name='place')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_services', to=settings.AUTH_USER_MODEL, verbose_name='reported by')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='monarp_places.service', verbose_name='service')),
            ],
        ),
    ]
