# Generated by Django 4.0.6 on 2022-07-07 17:46

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('monarp_places', '0002_service_rename_notes_place_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='is private'),
        ),
        migrations.AddField(
            model_name='place',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='website'),
        ),
        migrations.AddField(
            model_name='placeservice',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='description'),
        ),
    ]
